<?php defined('_ENGINE') or die('Access Denied'); return array (
  0 => 'Activity',
  1 => 'Advmenusystem',
  2 => 'Album',
  3 => 'Announcement',
  4 => 'Authorization',
  5 => 'Classified',
  6 => 'Core',
  7 => 'Custom',
  8 => 'Experience',
  9 => 'Fields',
  10 => 'Invite',
  11 => 'Messages',
  12 => 'Network',
  13 => 'Payment',
  14 => 'Question',
  15 => 'Storage',
  16 => 'Ultimatenews',
  17 => 'User',
  18 => 'Ynblog',
  19 => 'Ynfeed',
  20 => 'Ynmember',
  21 => 'Ynresponsive1',
  22 => 'Ynresponsiveclean',
  23 => 'Yntheme',
  24 => 'YounetCore',
); ?>