<?php echo '<?xml version="1.0" encoding="UTF-8"?>' ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your experience. -->
<!-- It contains information about your experience's posts, comments, and categories. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your experience. -->

<!-- To import this information into a WordPress experience follow these steps. -->
<!-- 1. Log in to that experience as an administrator. -->
<!-- 2. Go to Tools: Import in the experience's admin panels (or Manage: Import in older versions of WordPress). -->
<!-- 3. Choose "WordPress" from the list. -->
<!-- 4. Upload this file using the form provided on that page. -->
<!-- 5. You will first be asked to map the authors in this export file to users -->
<!--    on the experience.  For each author, you may choose to map to an -->
<!--    existing user on the experience or to create a new user -->
<!-- 6. WordPress will then import each of the posts, comments, and categories -->
<!--    contained in this file into your experience -->

<!-- generator="WordPress.com" created="2011-04-26 08:16"-->
<rss version="2.0"
     xmlns:excerpt="http://wordpress.org/export/1.0/excerpt/"
     xmlns:content="http://purl.org/rss/1.0/modules/content/"
     xmlns:wfw="http://wellformedweb.org/CommentAPI/"
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:wp="http://wordpress.org/export/1.0/"
>
<?php
$site_name = Engine_Api::_()->getApi('settings', 'core')->getSetting('core_general_site_title', $this->translate('_SITE_TITLE'));
?>
    <channel>
        <title><?php echo $this -> translate("%s's Experiences", $site_name)?></title>
        <link><?php echo "//".$_SERVER['HTTP_HOST'].$this->url(array(), 'experience_general');?></link>
        <description><?php echo $this -> translate("Just another WordPress.com site")?></description>
        <pubDate><?php date("D, d F Y G:i:s O")?></pubDate>
        <generator><?php echo "//".$_SERVER['HTTP_HOST']?></generator>
        <language>en</language>
        <wp:wxr_version>1.0</wp:wxr_version>
        <wp:base_site_url><?php echo "//".$_SERVER['HTTP_HOST']?></wp:base_site_url>
        <wp:base_experience_url><?php echo "//".$_SERVER['HTTP_HOST'].$this->url(array(), 'experience_general');?></wp:base_experience_url>
        <wp:category><wp:category_nicename></wp:category_nicename><wp:category_parent></wp:category_parent><wp:cat_name><![CDATA[]]></wp:cat_name></wp:category>
        <?php foreach ($this->experiences as $experience) :?>
            <item>
                <title><?php echo $experience->getTitle() ?></title>
                <link><?php echo "//".$_SERVER['HTTP_HOST']. $experience -> getHref(); ?></link>
                <pubDate><?php echo $experience->creation_date ?></pubDate>
                <dc:creator><![CDATA[<?php echo $experience -> getOwner() -> getTitle() ?>]]></dc:creator>
                    <category><![CDATA[]]></category>
                    <category domain="category" nicename=""><![CDATA[]]></category>
                <guid isPermaLink="false"><?php echo "//".$_SERVER['HTTP_HOST']. $experience -> getHref(); ?></guid>
                <description></description>
                <content:encoded><![CDATA[<?php echo $experience->body ?>]]></content:encoded>
                <excerpt:encoded><![CDATA[]]></excerpt:encoded>
                <wp:post_id><?php echo $experience->experience_id ?></wp:post_id>
                <wp:post_date><?php echo $experience->creation_date ?></wp:post_date>
                <wp:post_date_gmt><?php echo $experience->creation_date ?></wp:post_date_gmt>
                <wp:comment_status>open</wp:comment_status>
                <wp:ping_status>open</wp:ping_status>
                <wp:post_name><?php echo $experience->getTitle()?></wp:post_name>
                <wp:status>publish</wp:status>
                <wp:post_parent>0</wp:post_parent>
                <wp:menu_order>0</wp:menu_order>
                <wp:post_type>post</wp:post_type>
                <wp:post_password></wp:post_password>
                <wp:is_sticky>0</wp:is_sticky>
            </item>
        <?php endforeach;?>
    </channel>
</rss>
